### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by arthurvr** [hackerkid/ama#1]
Screenshot please. It tells a lot about somebody's personality.

**Comment by hackerkid** [comment]
Sorry for the late reply. Internet in India sucks big time. We have 3G only in limited places.  So I use my phone only for calling and texting. Hope you got my point. :)

**Comment by hackerkid** [comment]
So JIO started providing 4G Internet throughout India. This is how my screen looks like now. 

![screenshot_2017-01-19-19-23-30-892_com miui home](https://cloud.githubusercontent.com/assets/7190633/22109357/66abeee2-de7d-11e6-8e61-8d48b7eee7b8.png)
