### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [hackerkid/ama#3]
Editor, terminal, themes, fonts, etc.

**Comment by hackerkid** [comment]
I run Elementary OS in a Sony VAIO. 

My favorite text editors are `vi` and `subl`. In Sublime I  use the `Blackboard` color scheme and for vi I stick up with the default theme. 

I use ZSH as my primary Unix shell. I run `Pure` as the terminal prompt along with the the default color scheme of Elementary OS with some slight modifications. Thanks for making Pure. 

I don't have any preference for fonts usually. Currently I am using `Droid Sans Mono(12)` for my terminal.  

 I prefer Firefox  over Chrome.
