### ISSUE TITLE
What's your favorite place in India?

### ISSUE THREAD

**Issue by sindresorhus** [hackerkid/ama#4]

**Comment by hackerkid** [comment]
Kerala. Kerala is a beautiful state in Southern India. It is filled with backwaters and beautiful beaches. It is also my home state. Kerala has a warm climate through out the year.  Kerala is popularly known among tourists as `God's own country`. 

![Kerala Backwaters](http://www.goseekandhide.com/wp-content/uploads/2014/11/alleppey-backwaters.jpg) 

You should visit Kerala once :smiley:

**Comment by sindresorhus** [comment]
That looks stunning! Added to my travel list.

**Comment by melvin0008** [comment]
Even Ladakh and Goa are great places to visit in India. There's a lot of culture and tradition oozing out from every state in India. You will definitely like India :)

**Comment by shidhincr** [comment]
@sindresorhus You should visit Kerala once.. Let us know when you are planning
